/* Itihas — event deck
   year: integer, negative = BCE. approx: true when the date is conventional / circa.
   era keys: ancient, classical, medieval, early-modern, colonial, republic */
window.ITIHAS_EVENTS = [
  { year: -7000, approx: true, era: 'ancient', title: 'Farmers settle Mehrgarh', blurb: 'Wheat, barley and mud-brick houses at the foot of the Bolan Pass — South Asia’s first known farming village.' },
  { year: -2600, approx: true, era: 'ancient', title: 'Mohenjo-daro rises', blurb: 'The Indus cities hit their stride: grid streets, covered drains, standard bricks and the Great Bath.' },
  { year: -1500, approx: true, era: 'ancient', title: 'The Rigveda is composed', blurb: 'Over a thousand hymns are sung, memorised and passed down word-perfect for three millennia before being written.' },
  { year: -600, approx: true, era: 'ancient', title: 'The sixteen Mahajanapadas', blurb: 'Iron, coinage and cities return to the Ganges plain as sixteen great states compete for the river.' },
  { year: -528, approx: true, era: 'ancient', title: 'Siddhartha becomes the Buddha', blurb: 'Under a pipal tree at Bodh Gaya, a prince from Kapilavastu attains enlightenment.' },
  { year: -326, era: 'ancient', title: 'Alexander crosses the Indus', blurb: 'The Macedonian army meets Porus on the Jhelum. His troops refuse to march further east.' },
  { year: -321, approx: true, era: 'ancient', title: 'Chandragupta founds the Mauryan Empire', blurb: 'With Chanakya beside him, a young commander topples the Nandas and takes Pataliputra.' },
  { year: -261, approx: true, era: 'ancient', title: 'The Kalinga War', blurb: 'Ashoka conquers Kalinga at terrible cost, then renounces conquest by the sword.' },
  { year: -250, approx: true, era: 'ancient', title: 'Ashoka’s edicts are carved', blurb: 'Pillars and rock faces across the subcontinent carry the emperor’s words on dhamma.' },
  { year: -185, approx: true, era: 'ancient', title: 'Pushyamitra ends the Mauryas', blurb: 'The last Mauryan emperor is assassinated by his own general, who founds the Shunga dynasty.' },
  { year: 78, approx: true, era: 'classical', title: 'Kanishka takes the Kushan throne', blurb: 'The Kushan emperor’s reign links Gandhara, Mathura and the Silk Road; the Saka era begins.' },
  { year: 320, approx: true, era: 'classical', title: 'The Gupta Empire begins', blurb: 'Chandragupta I is crowned in Magadha, opening what later generations call a golden age.' },
  { year: 400, approx: true, era: 'classical', title: 'Kalidasa writes Shakuntala', blurb: 'At the Gupta court, the poet composes the play that Goethe would one day rhapsodise over.' },
  { year: 499, era: 'classical', title: 'Aryabhata publishes the Aryabhatiya', blurb: 'A 23-year-old in Kusumapura sets down sines, place value and a spinning Earth.' },
  { year: 630, approx: true, era: 'classical', title: 'Xuanzang reaches India', blurb: 'The Chinese monk arrives to study at Nalanda, leaving the richest travelogue of Harsha’s India.' },
  { year: 712, era: 'classical', title: 'Muhammad bin Qasim takes Sindh', blurb: 'An Umayyad army crosses the Indus delta and captures Debal, Nerun and Brahmanabad.' },
  { year: 788, approx: true, era: 'classical', title: 'Adi Shankara is born', blurb: 'The philosopher from Kaladi will walk the length of India and found four mathas.' },
  { year: 1010, era: 'medieval', title: 'The Brihadeeswarar Temple is consecrated', blurb: 'Rajaraja Chola completes the great granite temple at Thanjavur, its vimana 66 metres high.' },
  { year: 1025, era: 'medieval', title: 'Mahmud of Ghazni sacks Somnath', blurb: 'The seventeenth raid from Ghazni strips the temple on the Saurashtra coast.' },
  { year: 1192, era: 'medieval', title: 'Second Battle of Tarain', blurb: 'Muhammad of Ghor defeats Prithviraj Chauhan, opening the Ganges plain to the Ghurids.' },
  { year: 1206, era: 'medieval', title: 'The Delhi Sultanate is founded', blurb: 'Qutb al-Din Aibak, once a slave, becomes the first sultan of Delhi.' },
  { year: 1236, era: 'medieval', title: 'Razia becomes Sultan of Delhi', blurb: 'The only woman to rule the Sultanate is enthroned, and reigns for three and a half years.' },
  { year: 1336, era: 'medieval', title: 'Vijayanagara is founded', blurb: 'Harihara and Bukka build a capital on the Tungabhadra that will dazzle Persian and Portuguese visitors.' },
  { year: 1398, era: 'medieval', title: 'Timur sacks Delhi', blurb: 'The Central Asian conqueror shatters the Tughlaq Sultanate and marches home with the loot.' },
  { year: 1469, era: 'medieval', title: 'Guru Nanak is born', blurb: 'In the village of Talwandi near Lahore, the founder of the Sikh faith is born.' },
  { year: 1498, era: 'early-modern', title: 'Vasco da Gama lands at Calicut', blurb: 'The Portuguese captain reaches the Malabar coast, and the sea route to Europe opens.' },
  { year: 1526, era: 'early-modern', title: 'First Battle of Panipat', blurb: 'Babur’s artillery breaks Ibrahim Lodi’s army. The Mughal Empire begins.' },
  { year: 1556, era: 'early-modern', title: 'Akbar is crowned', blurb: 'A thirteen-year-old becomes emperor on a brick platform at Kalanaur.' },
  { year: 1565, era: 'early-modern', title: 'Battle of Talikota', blurb: 'The Deccan sultanates combine to crush Vijayanagara, and Hampi is abandoned.' },
  { year: 1600, era: 'early-modern', title: 'The East India Company is chartered', blurb: 'Elizabeth I grants a monopoly on English trade east of the Cape to a company of London merchants.' },
  { year: 1632, era: 'early-modern', title: 'Work begins on the Taj Mahal', blurb: 'Shah Jahan commissions a tomb for Mumtaz Mahal on the banks of the Yamuna at Agra.' },
  { year: 1674, era: 'early-modern', title: 'Shivaji is crowned at Raigad', blurb: 'The Maratha leader takes the title Chhatrapati in a ceremony that took months to prepare.' },
  { year: 1707, era: 'early-modern', title: 'Aurangzeb dies in the Deccan', blurb: 'The last of the great Mughals dies at Ahmednagar, and the empire begins to fracture.' },
  { year: 1739, era: 'early-modern', title: 'Nader Shah carries off the Peacock Throne', blurb: 'The Persian invader sacks Delhi and leaves with the Koh-i-Noor.' },
  { year: 1757, era: 'colonial', title: 'Battle of Plassey', blurb: 'Clive defeats Siraj ud-Daulah in a mango grove in Bengal, largely through bribery.' },
  { year: 1761, era: 'colonial', title: 'Third Battle of Panipat', blurb: 'Ahmad Shah Durrani routs the Marathas in one of the bloodiest single days of the century.' },
  { year: 1799, era: 'colonial', title: 'Tipu Sultan falls at Srirangapatna', blurb: 'The Tiger of Mysore dies defending his capital against the Company’s siege.' },
  { year: 1829, era: 'colonial', title: 'Sati is outlawed', blurb: 'Lord Bentinck’s regulation, urged on by Raja Ram Mohan Roy, bans the burning of widows.' },
  { year: 1853, era: 'colonial', title: 'The first passenger train runs', blurb: 'Fourteen carriages pulled by three locomotives travel from Bombay to Thane in about an hour.' },
  { year: 1857, era: 'colonial', title: 'The Revolt of 1857', blurb: 'Sepoys at Meerut rise, march to Delhi and proclaim Bahadur Shah Zafar emperor.' },
  { year: 1858, era: 'colonial', title: 'The Crown takes over from the Company', blurb: 'The Government of India Act transfers rule to Queen Victoria; the Raj proper begins.' },
  { year: 1885, era: 'colonial', title: 'The Indian National Congress is founded', blurb: 'Seventy-two delegates meet in Bombay at the Gokuldas Tejpal Sanskrit College.' },
  { year: 1905, era: 'colonial', title: 'Bengal is partitioned', blurb: 'Curzon splits the province, igniting the Swadeshi movement and the boycott of British goods.' },
  { year: 1911, era: 'colonial', title: 'The capital moves to Delhi', blurb: 'At the Delhi Durbar, George V announces the move from Calcutta and the reunion of Bengal.' },
  { year: 1913, era: 'colonial', title: 'Tagore wins the Nobel Prize', blurb: 'Gitanjali makes Rabindranath the first non-European Nobel laureate in literature.' },
  { year: 1919, era: 'colonial', title: 'Jallianwala Bagh', blurb: 'General Dyer’s troops fire on a crowd in Amritsar for ten minutes.' },
  { year: 1930, era: 'colonial', title: 'The Salt March', blurb: 'Gandhi walks 385 kilometres from Sabarmati to Dandi and picks up a lump of salt.' },
  { year: 1943, era: 'colonial', title: 'The Bengal Famine', blurb: 'Wartime policy, hoarding and a cyclone kill some three million people in Bengal.' },
  { year: 1947, era: 'republic', title: 'Independence and Partition', blurb: 'At the stroke of midnight, India awakes to freedom; the Radcliffe Line divides Punjab and Bengal.' },
  { year: 1950, era: 'republic', title: 'The Constitution comes into force', blurb: 'On 26 January, India becomes a republic under the longest written constitution in the world.' },
  { year: 1951, era: 'republic', title: 'The first general election begins', blurb: 'Some 173 million people, most of them unable to read, vote using picture symbols on the ballot boxes.' },
  { year: 1955, era: 'republic', title: 'Pather Panchali is released', blurb: 'Satyajit Ray’s debut, shot on weekends on borrowed money, changes Indian cinema.' },
  { year: 1961, era: 'republic', title: 'Goa joins India', blurb: 'Operation Vijay ends four and a half centuries of Portuguese rule in thirty-six hours.' },
  { year: 1962, era: 'republic', title: 'The Sino-Indian War', blurb: 'Chinese forces cross the McMahon Line in the Himalayas; the war lasts a month.' },
  { year: 1969, era: 'republic', title: 'ISRO is founded', blurb: 'Vikram Sarabhai’s space programme gets its own organisation, headquartered in Bangalore.' },
  { year: 1971, era: 'republic', title: 'The Bangladesh Liberation War', blurb: 'A thirteen-day war ends with the surrender at Dhaka and the birth of Bangladesh.' },
  { year: 1974, era: 'republic', title: 'Smiling Buddha', blurb: 'India tests its first nuclear device under the Rajasthan desert at Pokhran.' },
  { year: 1975, era: 'republic', title: 'The Emergency is declared', blurb: 'Indira Gandhi suspends elections and civil liberties for twenty-one months.' },
  { year: 1983, era: 'republic', title: 'India wins the Cricket World Cup', blurb: 'Kapil Dev’s side beats the West Indies at Lord’s, defending a total of just 183.' },
  { year: 1984, era: 'republic', title: 'The Kolkata Metro opens', blurb: 'India’s first metro runs from Esplanade to Bhowanipore, 3.4 kilometres underground.' },
  { year: 1991, era: 'republic', title: 'The economy is opened up', blurb: 'Facing a balance-of-payments crisis, Manmohan Singh’s budget dismantles the licence raj.' },
  { year: 1998, era: 'republic', title: 'Pokhran-II', blurb: 'Five nuclear tests in three days; India declares itself a nuclear weapons state.' },
  { year: 2008, era: 'republic', title: 'Chandrayaan-1 reaches the Moon', blurb: 'ISRO’s first lunar mission finds water molecules on the lunar surface.' },
  { year: 2011, era: 'republic', title: 'Namma Metro opens in Bangalore', blurb: 'The first stretch runs from Baiyappanahalli to M.G. Road; today it carries hundreds of thousands a day.' },
  { year: 2014, era: 'republic', title: 'Mangalyaan enters Mars orbit', blurb: 'India becomes the first nation to reach Mars on its first attempt, for less than the budget of Gravity.' },
  { year: 2016, era: 'republic', title: 'Demonetisation', blurb: 'At 8 p.m. on 8 November, 86 per cent of India’s cash is declared invalid from midnight.' },
  { year: 2023, era: 'republic', title: 'Chandrayaan-3 lands near the lunar south pole', blurb: 'Vikram touches down on 23 August; India is the first to land near the Moon’s south pole.' }
];
